version: "3.7"

services:
  n8n:
    image: n8nio/n8n:1.97.1
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_DEPLOYMENT_TYPE=${N8N_DEPLOYMENT_TYPE}
      - N8N_DIAGNOSTICS_ENABLED=${N8N_DIAGNOSTICS_ENABLED}
      - N8N_HOST=${N8N_HOST}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - N8N_EMAIL_MODE=${N8N_EMAIL_MODE}
      - N8N_USER_MANAGEMENT_DISABLED=${N8N_USER_MANAGEMENT_DISABLED}
      - N8N_ADMIN_EMAIL=${N8N_ADMIN_EMAIL}
      - N8N_ADMIN_PASSWORD=${N8N_ADMIN_PASSWORD}
      - N8N_SECURE_COOKIE=${N8N_SECURE_COOKIE}
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped
    networks:
      - senna_net

  senna_project:
    build:
      context: .                          # contexto = raiz do repo
      dockerfile: senna-project/Dockerfile
    image: senna_project:latest
    container_name: senna_project
    ports:
      - "5001:5001"
    # Monte APENAS os diretórios de dados no caminho correto do projeto dentro do container
    volumes:
      - ./senna-project/maps:/app/senna-project/maps
      - ./senna-project/logs:/app/senna-project/logs
      - ./senna-project/customers:/app/senna-project/customers
    environment:
      - PYTHONUNBUFFERED=1
      # Não sobrescreva PYTHONPATH aqui (já setado no Dockerfile para /app/senna-project)
    restart: unless-stopped
    networks:
      - senna_net

volumes:
  n8n_data:

networks:
  senna_net:
    driver: bridge